name: udharokhata
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  sqflite: ^1.1.0
  path_provider: ^1.6.8
  autocomplete_textfield: ^1.7.3
  image_picker: ^0.6.0+17
  simple_moment: ^1.0.2
  flutter_archive: ^0.1.4
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^4.4.6
  googleapis: ^0.55.0
  googleapis_auth: ^0.2.11+1
  flutter_secure_storage: ^3.3.3
  path: ^1.6.4
  url_launcher: ^5.4.7
  archive: ^2.0.13
  pdf: ^1.8.1
  intl: ^0.16.1
  open_file: ^3.0.1
  share: ^0.6.5
  flutter_pdfview: ^1.0.3+3
  cron: ^0.2.3
  background_fetch: ^0.5.1
  shared_preferences: ^0.5.10
  provider: ^4.3.2+2
  back_button_interceptor: ^4.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand/Quicksand-Regular.ttf
        - asset: fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
  assets:
    - images/no_image.jpg
    - images/noimage_person.png
    - images/google_logo.png
    - images/cv_template.png
    - images/share.png
    - images/backup.png
    - images/business.png
    - images/data-copy.jpg
    - images/cv/email.png
    - images/cv/phone.png
    - images/cv/location.png
    - images/cv/website.png
